@AspireYouTubeSummariser.ApiApp_HostAddress = https://localhost:5051

GET {{AspireYouTubeSummariser.ApiApp_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{AspireYouTubeSummariser.ApiApp_HostAddress}}/summary
Accept: text/plain
Content-Type: application/json

{
  "videoUrl": "https://www.youtube.com/watch?v=YolWosck5a0",
  "videoLanguageCode": "en",
  "summaryLanguageCode": "en"
}